module.exports = {
  topicComponentToDto: ({
    topic_component_id,
    component_type,
    rich_text_id,
    material_id,
    forum_id,
    submission_id,
    content,
    forum_title,
    forum_description,
    submission_title,
    submission_description,
    title,
    description,
    due_date,
    url,
    file_name,
  }) => ({
    ...(topic_component_id && { topicComponentId: topic_component_id }),
    ...(component_type && { componentType: component_type }),
    ...(content && { content }),
    ...(url && { url }),
    ...(title && { title }),
    ...(description && { description }),
    ...(forum_title && { title: forum_title }),
    ...(forum_description && { description: forum_description }),
    ...(submission_title && { title: submission_title }),
    ...(submission_description && { description: submission_description }),
    ...(due_date && { dueDate: due_date }),
    ...(forum_id && { forumId: forum_id }),
    ...(rich_text_id && { richTextId: rich_text_id }),
    ...(material_id && { materialId: material_id }),
    ...(submission_id && { submissionId: submission_id }),
    ...(file_name && { fileName: file_name }),
  }),
};
