module.exports = {
  userToDto: ({
    user_id,
    username,
    password,
    user_type,
    name,
    birthday,
    gender,
    race,
    religion,
    address,
    tel_no,
    hp_no,
    email,
    teacher_id,
    student_id,
  }) => ({
    ...(user_id && { userId: user_id }),
    ...(username && { username }),
    ...(password && { password }),
    ...(user_type && { userType: user_type }),
    ...(name && { name }),
    ...(birthday && { birthday }),
    ...(gender && { gender }),
    ...(race && { race }),
    ...(religion && { religion }),
    ...(address && { address }),
    ...(tel_no && { telNo: tel_no }),
    ...(hp_no && { hpNo: hp_no }),
    ...(email && { email }),
    ...(teacher_id && { teacherId: teacher_id }),
    ...(student_id && { studentId: student_id }),
  }),
};
